name: Update site

on:
  workflow_dispatch:            # manual run
  schedule:
    - cron: '00 23 * * 2'       # tuesdays at 23 UTC

permissions:
  contents: write               # required to push back

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas beautifulsoup4 requests lxml openpyxl

      - name: Run generator
        run: |
          python tabell_generator.py   # must write index.html in repo root

      - name: Commit and push ALL changes
        run: |
          # Only commit if there are any changes (added/modified/deleted)
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add -A
            git commit -m "Auto-update ($(date -u +'%Y-%m-%d %H:%M:%S') UTC)"
            git push
          else
            echo "No changes to commit."
          fi
