name: Update index.html

on:
  workflow_dispatch:           # manual "Run workflow" button
  schedule:
    - cron: '21 15 * * *'      # every day 21:15

permissions:
  contents: write              # allow the job to push back to the repo

concurrency:
  group: update-index
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas beautifulsoup4 requests lxml openpyxl

      - name: Run generator
        run: |
          python tabell_generator.py

      - name: Commit and push if changed
        run: |
          if [[ -n "$(git status --porcelain)" ]]; then
            git config user.name  "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add index.html
            git commit -m "Auto-update index.html ($(date -u +'%Y-%m-%d %H:%M:%S') UTC)"
            git push
          else
            echo "No changes to commit."
          fi
